set number
set ruler
set showmatch
set hidden
set background=dark
set laststatus=2
set relativenumber
set hidden
set cursorline
set pastetoggle=<F12>
set incsearch
set hlsearch
set autoindent
set encoding=utf-8
"set fileencodings=iso-2022-jp,cp932,sjis,euc-jp,utf-8
set colorcolumn=80,100
set noswapfile
set backspace=indent,eol,start
