"set fileencodings=iso-2022-jp,cp932,sjis,euc-jp,utf-8
"set visualbell t_vb=
set ambiwidth=double
set autoindent
set background=dark
set backspace=indent,eol,start
set belloff=all
set colorcolumn=80,100
set cursorline
set hidden
set hidden
set history=5000
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set noswapfile
set number
set pastetoggle=<F12>
set relativenumber
set ruler
set showmatch
set smartcase
set wildmenu
